repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.8
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi]
        args: [--fix, --select, I]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.5.2
    hooks:
      # Compile requirements
      - id: pip-compile
        args: [pyproject.toml, -o, requirements.txt]
  - repo: https://github.com/biomejs/pre-commit
    rev: "v0.5.0" # Use the sha / tag you want to point at
    hooks:
      - id: biome-format
        exclude: \.min\.(js|css|html)$
        additional_dependencies: ["@biomejs/biome@1.9.4"]
        args: [--indent-style=space]
